Repository accounts-js/accounts, pull requests merged in 2018-07, with the labels that each got.

#365 graphql remove the `email` key on the user and the `CreateUserProfileInput` type
  packages/graphql-api/README.md
  packages/graphql-api/package.json
  packages/graphql-api/src/graphql/types.ts
  packages/graphql-api/src/resolvers/user.ts
  packages/graphql-api/src/schema-builder.ts
  packages/graphql-api/src/types/graphql.ts
  packages/graphql-api/src/utils/context-builder.ts
  packages/graphql-client/src/graphql-client.ts
Labels: breaking change

#366 feat: @authenticated directive
  packages/graphql-api/README.md
  packages/graphql-api/package.json
  packages/graphql-api/src/index.ts
  packages/graphql-api/src/schema-builder.ts
  packages/graphql-api/src/utils/authenticated-directive.ts
  packages/graphql-api/src/utils/authenticated-resolver.ts
  packages/graphql-api/src/utils/context-builder.ts
  yarn.lock
Labels: breaking change, enhancement

#369 Fix infinite loop issue during token refresh for graphql-client
  packages/graphql-client/package.json
  packages/graphql-client/src/graphql-client.ts
  yarn.lock
Labels: bug

#380 Required reason token for the database interface
  packages/database-mongo/__tests__/index.ts
  packages/database-mongo/src/mongo.ts
  packages/password/__tests__/accounts-password.ts
  packages/password/package.json
  packages/password/src/accounts-password.ts
  packages/types/src/types/database-interface.ts
Labels: Internal

#382 Fix apollo-link-accounts types
  packages/apollo-link-accounts/package.json
  packages/apollo-link-accounts/src/index.ts
  yarn.lock
Labels: bug

#401 Also encrypt the old password when trying to change it
  packages/client-password/__tests__/client-password.ts
  packages/client-password/src/client-password.ts
Labels: bug
